import type { Metadata } from "next";

import { Titillium_Web } from "next/font/google";

import { ThemeProvider } from "./providers/themeProvider";

import "./styles/styles.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const titillium = Titillium_Web({
  weight: ["200", "300", "400", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={titillium.className}>
        <div className="wrapper">
          <ThemeProvider>{children}</ThemeProvider>
        </div>
      </body>
    </html>
  );
}
